NorthWindWeb/Controllers/CoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NorthWindWeb.Models;

namespace NorthWindWeb.Controllers
{
    public class CoreController : Controller
    {
        // GET: Core
        public ActionResult Index(Customer m)
        {
            return View(m);
        }
        public ActionResult Menu()
        {
             return View();


        }
    }
}

NorthWindWeb/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NorthWindWeb.Models;
using Newtonsoft.Json;
using System.Web.Http;

namespace NorthWindWeb.Controllers
{
    
    public class CustomerController : Controller
    {
        private string connStr = @"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=c:\users\芮君\source\repos\NorthWindWeb\NorthWindWeb\App_Data\northwnd.mdf;Integrated Security = True";
        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }

        [System.Web.Http.HttpPost]
        public JsonResult Add([FromBody]Customer AddCus)
        {
            if(ModelState.IsValid && !String.IsNullOrEmpty(AddCus.CustomerID) && !String.IsNullOrEmpty(AddCus.CompanyName))
            {
                string addnull = "nadd";
                string pk = "pk";
                SqlConnection conn = new SqlConnection(connStr);
                SqlCommand cmd = new SqlCommand(@"insert into Customers(CustomerID, 
                                                                                                                    CompanyName,
                                                                                                                    ContactName,
                                                                                                                    ContactTitle,
                                                                                                                    Address,
                                                                                                                    City,Region,
                                                                                                                    PostalCode,
                                                                                                                    Country,
                                                                                                                    Phone,
                                                                                                                    Fax)
                                                                                                          values(@CustomerID,
                                                                                                                    @CompanyName,
                                                                                                                    @ContactName,
                                                                                                                    @ContactTitle,
                                                                                                                    @Address,
                                                                                                                    @City,
                                                                                                                    @Region,
                                                                                                                    @PostalCode,
                                                                                                                    @Country,
                                                                                                                    @Phone,
                                                                                                                    @Fax)", conn);
                cmd.Parameters.Add(new SqlParameter("@CustomerID", AddCus.CustomerID ?? pk));
                cmd.Parameters.Add(new SqlParameter("@CompanyName", AddCus.CompanyName ?? addnull));
                cmd.Parameters.Add(new SqlParameter("@ContactName", (object)AddCus.ContactName ?? DBNull.Value));
                cmd.Parameters.Add(new SqlParameter("@ContactTitle", (object)AddCus.ContactTitle ?? DBNull.Value));
                cmd.Parameters.Add(new SqlParameter("@Address", (object)AddCus.Address ?? DBNull.Value));
                cmd.Parameters.Add(new SqlParameter("@City", (object)AddCus.City ?? DBNull.Value));
                cmd.Parameters.Add(new SqlParameter("@Region", (object)AddCus.Region ?? DBNull.Value));
                cmd.Parameters.Add(new SqlParameter("@PostalCode", (object)AddCus.PostalCode ?? DBNull.Value));
                cmd.Parameters.Add(new SqlParameter("@Country", (object)AddCus.Country ?? DBNull.Value));
                cmd.Parameters.Add(new SqlParameter("@Phone", (object)AddCus.Phone ?? DBNull.Value));
                cmd.Parameters.Add(new SqlParameter("@Fax", (object)AddCus.Fax ?? DBNull.Value));
                conn.Open();
                cmd.ExecuteNonQuery();
                conn.Close();
            }
            else
            {
                return Json(new {staus="新增失敗"});
            }

            return Json(new { staus="新增成功"});
        }
        public ActionResult Edit()
        {

            return View();
        }
        public ActionResult Insert()
        {
         
            return View();
        }
        public ActionResult Update()
        {
            return View();
        }
        public ActionResult Delete()
        {
            return View();
        }
        public JsonResult Query(Customer cus)
        {
            //新增一個DataTable資料容器
            DataTable dt = new DataTable();
            //建立資料庫連結
            SqlConnection conn = new SqlConnection(connStr);
            //撰寫SQL語法
            //SqlCommand cmd = new SqlCommand(@"select*from Customers where (datalength(@CustomerID) = 0 or  CustomerID=@CustomerID)", conn);
            SqlCommand cmd = new SqlCommand(@"select*from Customers where (@CustomerID is null or  CustomerID=@CustomerID)", conn);
            //SqlCommand cmd = new SqlCommand(@"select*from Customers where CustomerID=@CustomerID 
            //                                                                                                               and CompanyName=@CompanyName 
            //                                                                                                               and ContactTitle=@ContactTitle 
            //                                                                                                               and Address=@Address 
            //                                                                                                               and City=@City 
            //                                                                                                               and Region=@Region 
            //                                                                                                               and Country=@Country 
            //                                                                                                               and Phone=@Phone 
            //                                                                                                               and Fax=@Fax", conn);
            //cmd.Parameters.Add(new SqlParameter("@CustomerID", cus.CustomerID??DBNull.Value.ToString()));
            cmd.Parameters.Add(new SqlParameter("@CustomerID", (object)cus.CustomerID ?? DBNull.Value));
            //cmd.Parameters.Add(new SqlParameter("@CompanyName", cus.CompanyName));
            //cmd.Parameters.Add(new SqlParameter("@ContactTitle", cus.ContactTitle));
            //cmd.Parameters.Add(new SqlParameter("@Address", cus.Address));
            //cmd.Parameters.Add(new SqlParameter("@City", cus.City));
            //cmd.Parameters.Add(new SqlParameter("@Region", cus.Region));
            //cmd.Parameters.Add(new SqlParameter("@Country", cus.Country));
            //cmd.Parameters.Add(new SqlParameter("@Phone", cus.Phone));
            //cmd.Parameters.Add(new SqlParameter("@Fax", cus.Fax));
            //打開資料庫連結
            conn.Open();
            //建立資料讀取器
            SqlDataAdapter ad = new SqlDataAdapter(cmd);
            //將讀取的資料放入DataTable
            ad.Fill(dt);
          
            List<Customer> getCustomerList = new List<Customer>();
                  {
                for (int i = 0; i< dt.Rows.Count; i++)
                {
                    Customer prodBasic = new Customer();
                    prodBasic.CustomerID = dt.Rows[i]["CustomerID"].ToString();
                    prodBasic.CompanyName = dt.Rows[i]["CompanyName"].ToString();
                    prodBasic.ContactName = dt.Rows[i]["ContactName"].ToString();
                    prodBasic.ContactTitle =dt.Rows[i]["ContactTitle"].ToString();
                    prodBasic.Address = dt.Rows[i]["Address"].ToString();
                    prodBasic.City = dt.Rows[i]["City"].ToString();
                    prodBasic.Region =dt.Rows[i]["Region"].ToString();
                    prodBasic.Country = dt.Rows[i]["Country"].ToString();
                    prodBasic.Phone = dt.Rows[i]["Phone"].ToString();
                    prodBasic.Fax =dt.Rows[i]["Fax"].ToString();


                    getCustomerList.Add(prodBasic);
                }
            }
            return Json(getCustomerList);
        }
    }
}

NorthWindWeb/Controllers/UserController.cs
using Newtonsoft.Json.Linq;
using NorthWindWeb.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;


namespace NorthWindWeb.Controllers
{
    public class UserController : Controller
    {
        UserLogin m = new UserLogin();
        private string connStr = @"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=c:\users\芮君\source\repos\NorthWindWeb\NorthWindWeb\App_Data\northwnd.mdf;Integrated Security = True";

        // GET: User
        [Authorize]
        public ActionResult Index()
        {
            var UserData = JObject.Parse(((FormsIdentity)User.Identity).Ticket.UserData);
            ViewBag.UserName = (String)UserData["UserName"];
            return View();


        }
        public ActionResult Login(String UserID= "" , String Password = "", Boolean IsPersistent = false, String ReturnUrl = "Index")
        {
            if (!String.IsNullOrEmpty(Request.Form.Get("SignIn")))
            {
                //新增一個DataTable資料容器
                DataTable dt = new DataTable();
                //建立資料庫連結
                SqlConnection conn = new SqlConnection(connStr);
                //撰寫SQL語法
                SqlCommand cmd = new SqlCommand(@"select Username from UserProfile where UserID=@UserID and Password=@Password", conn);
                cmd.Parameters.Add(new SqlParameter("@UserID", UserID));
                cmd.Parameters.Add(new SqlParameter("@Password", Password));
                cmd.Parameters.Add(new SqlParameter("@IsPersistent", IsPersistent));
                //打開資料庫連結
                conn.Open();
                //建立資料讀取器
                SqlDataAdapter ad = new SqlDataAdapter(cmd);
                //將讀取的資料放入DataTable
                ad.Fill(dt);
                if (ModelState.IsValid && dt.Rows.Count > 0 && UserID.Length > 0 && Password.Length > 0)
                {
                    String Username2 = dt.Rows[0][0].ToString();
                    string UserData = JObject.FromObject(new { UserName = Username2, Age = 18 }).ToString();

                    FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(1, UserID,
                            DateTime.Now, DateTime.Now.AddMinutes(30), IsPersistent,
                            UserData, FormsAuthentication.FormsCookiePath);
                    HttpCookie cookie = new HttpCookie(FormsAuthentication.FormsCookieName, FormsAuthentication.Encrypt(ticket));
                    if (IsPersistent)
                    {
                        cookie.Expires = DateTime.Now.AddYears(1);
                    }
                    Response.Cookies.Add(cookie);
                }
                else
                {
                    ModelState.AddModelError(
                        "Password", "您輸入的帳號或密碼錯誤,請重新輸入!"
                        );
                    if (!ModelState.IsValidField("Password"))
                    {
                        var emptyValue = new ValueProviderResult(
                            string.Empty,
                            string.Empty,
                            System.Globalization.CultureInfo.CurrentCulture);

                        ModelState.SetModelValue(
                            "Password",
                            emptyValue);
                    }
                    return View(m);
                }
                return Redirect(ReturnUrl);
            }
            else
            {
                return View();
            }
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index");   
        }
    }
}

NorthWindWeb/Views/User/Index.cshtml
@model NorthWindWeb.Models.Customer_Query
@{
    ViewBag.Title = "Index";
}
@{
    Layout = "~/Views/Shared/_LayoutNorthWind.cshtml";
}
@section scripts{
    <script>
        var aUrl = function (e) {
            var itm = e.item;
            var attr = $(itm).attr('url');

            if (typeof attr !== typeof undefined && attr !== false) {
                window.location = attr;
            }
        }
        $('#time').kendoPanelBar(
            // access an existing PanelBar instance
            {
                select: aUrl
            }
        );

        function objectifyForm(formArray) {
            //serialize data function
            var returnArray = {};``
            for (var i = 0; i < formArray.length; i++) {
                returnArray[formArray[i]['name']] = formArray[i]['value'];
            }
            return returnArray;
        }
        //KendoGrid
        $("#grid").kendoGrid({
            pageable: true,
            columns: [
                { field: "CustomerID", title: "客戶編號" },
                { field: "CompanyName", title: "公司名稱" },
                { field: "ContactName", title: "連絡人姓名" },
                { field: "ContactTitle", title: "連絡人職稱" },
                {
                    command: [{ name: 'edit', text: '編輯' },
                    { name: 'destroy', text: '刪除' }]
                }]
        });
        //Button Query function
        $("#btnQuery").on("click", function () {
            var DataSource = new kendo.data.DataSource({
                transport: {
                    read: {
                        url: "@Url.Action("Query","Customer")",
                        contentType: "application/json",
                        cache: false,
                        type: "POST",
                        async: false,

                    },
                    parameterMap: function (options) {
                        var jobj = objectifyForm($('#QueryForm').serializeArray());
                        return JSON.stringify(jobj);
                    }
                },
                pageSize: 10
            });
            $("#grid").data('kendoGrid').setDataSource(DataSource);
        });

        //Button Clear function
        $("#btnClear").on("click", function () {
            document.getElementById("QueryForm").reset(),
                $('#grid').data('kendoGrid').dataSource.data([]);  
        });

        //Button Add function
        $("#btnadd").click(function () {
            $("#AddWindow").data("kendoWindow").center().open();
  
        });

        //Kendowindow Add Setting
          $(document).ready(function () {
                   $("#AddWindow").kendoWindow({
            content: {
               url: "@Url.Action("Insert", "Customer")"
            },
            width: "600px",
            modal: true,
            title: "新增客戶資料",
                visible: false,
                actions: [
                    "Pin",
                    "Minimize",
                    "Maximize",
                    "Close"
                ]
              });                
        });
    </script>
}
<h1>客戶查詢</h1>
@using (Html.BeginForm("index", "Core", FormMethod.Post, new { id = "QueryForm" }))
{
    <table class="table table-bordered">
        <tr>
            <td>@Html.LabelFor(m => m.CustomerID)</td>
            <td>@Html.TextBoxFor(m => m.CustomerID,new {@class ="form-control"}) @Html.ValidationMessageFor(m => m.CustomerID)</td>
            <td>@Html.LabelFor(m => m.CompanyName)</td>
            <td>@Html.TextBoxFor(m => m.CompanyName,new {@class ="form-control" }) @Html.ValidationMessageFor(m => m.CompanyName)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(m => m.ContactName)</td>
            <td>@Html.TextBoxFor(m => m.ContactName,new {@class ="form-control"})@Html.ValidationMessageFor(m => m.ContactName)</td>
            <td>@Html.LabelFor(m => m.ContactTitle)</td>
            <td>@Html.TextBoxFor(m => m.ContactTitle, new {@class ="form-control"})@Html.ValidationMessageFor(m => m.ContactTitle)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(m => m.Address)</td>
            <td>@Html.TextBoxFor(m => m.Address,new {@class="form-control" })@Html.ValidationMessageFor(m => m.Address)</td>
            <td>@Html.LabelFor(m => m.City)</td>
            <td>@Html.TextBoxFor(m => m.City,new { @class="form-control"})@Html.ValidationMessageFor(m => m.City)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(m => m.Region)</td>
            <td>@Html.TextBoxFor(m => m.Region, new { @class = "form-control" })@Html.ValidationMessageFor(m => m.Region)</td>
            <td>@Html.LabelFor(m => m.PostalCode)</td>
            <td>@Html.TextBoxFor(m => m.PostalCode, new { @class = "form-control" })@Html.ValidationMessageFor(m => m.PostalCode)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(m => m.Country)</td>
            <td>@Html.TextBoxFor(m => m.Country, new { @class = "form-control" })@Html.ValidationMessageFor(m => m.Country)</td>
            <td>@Html.LabelFor(m => m.Phone)</td>
            <td>@Html.TextBoxFor(m => m.Phone, new { @class = "form-control" })@Html.ValidationMessageFor(m => m.Phone)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(m => m.Fax)</td>
            <td>@Html.TextBoxFor(m => m.Fax, new { @class = "form-control" })@Html.ValidationMessageFor(m => m.Fax)</td>
        </tr>
    </table>
}

    <div class="row">
        <div class="col-md-2">
            <button class="btn btn-success btn-block" id="btnadd">新增</button>
        </div>
        <div class="col-md-2">
            <button class="btn btn-success btn-block" id="btnQuery">查詢</button>
            </div>
            <div class="col-md-2">
                <button class="btn btn-success btn-block" id="btnClear">清除</button>
            </div>
        </div>
            <div id="grid"></div>
            <div id="AddWindow"></div>

NorthWindWeb/Views/User/Login.cshtml
@model NorthWindWeb.Models.UserLogin

@*@{
        ViewBag.Title = "Login";
    }*@


@*@Html.EditorForModel()

    <button type="submit" name="SignIn" value="登入">確定</button>
    <button type="reset">取消</button>*@
@*@{
        Html.EnableClientValidation(true);
        Html.EnableUnobtrusiveJavaScript(true);
    }*@


@*@using (Html.BeginForm("Login", "User"))
    {
        <table class="table table-bordered">
            <tr>
                <td>帳號</td>
                <td>@Html.TextBoxFor(m => m.UserID)</td>
                <td>@Html.ValidationMessageFor(m => m.UserID)</td>
            </tr>
            <tr>
                <td>密碼</td>
                <td>@Html.PasswordFor(m=>m.Password)</td>
                <td>@Html.ValidationMessageFor(m=>m.Password)</td>
            </tr>
            <tr>
                <td colspan="2">@Html.CheckBox("IsPersistent", false) 保持登入狀態</td>
            </tr>
            <tr>
                <td><button type="submit" name="SignIn" value="登入">確定</button></td>
                <td><button type="reset">取消</button></td>
            </tr>
        </table>
    }*@


@*<table class="table table-bordered">
        <tr>
            <td width="150px">@Html.LabelFor(m => m.UserID)</td>
            <td>@Html.TextBoxFor(m => m.UserID, new { @class = "form-group input-lg", }) @Html.ValidationMessageFor(m => m.UserID, "", new { @class = "text-danger" })</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(m => m.Password)</td>
            <td>@Html.PasswordFor(m => m.Password, new { @class = "form-group input-lg" }) @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })</td>
        </tr>
        <tr>
            <td colspan="2">@Html.CheckBoxFor(m => m.IsPersistent) @Html.LabelFor(m => m.IsPersistent)</td>
        </tr>
        <tr>
            <td><button class=" btn btn-success" type="submit" name="SignIn" value="登入">確定</button></td>
            <td><button class=" btn btn-success" type="reset">取消</button></td>
        </tr>
    </table>*@

@*@using (Html.BeginForm("Login", "User", FormMethod.Post, new { id = "LoginForm" }))
{
    <div class="container">
        <div class="row mx-auto">
            <div class="col-md-6 col-md-offset-3" id="LoginFormsize">
                <h2>會員登入</h2>
                <h2>
                    <hr class="colorgraph">
                </h2>
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div class="form-group">
                            <h4> @Html.LabelFor(m => m.UserID)</h4>
                        </div>
                    </div>
                    <div class="col-md-8 col-md-offset-2">
                        <div class="form-group">
                            <div class="col-md-12 input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span> @Html.TextBoxFor(m => m.UserID, new { @class = "form-control" }) @Html.ValidationMessageFor(m => m.UserID, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div class="form-group">
                            <h4> @Html.LabelFor(m => m.Password)</h4>
                        </div>
                    </div>
                    <div class="col-md-8 col-md-offset-2">
                        <div class="form-group">
                            <div class="col-md-12 input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-hand-right"></i></span> @Html.PasswordFor(m => m.Password, new { @class = "form-control" }) @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-2 col-md-2"></div>
                </div>
                <hr class="colorgraph">
                <div class="row">
                    <div class="col-md-6">
                        <button class=" btn btn-primary btn-block btn-lg" type="submit" name="SignIn" value="登入">確定</button>
                    </div>
                    <div class="col-md-6">
                        <button class=" btn btn-success btn-block btn-lg" type="reset">取消</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}*@

<div class="container">
    @using (Html.BeginForm("Login", "User", FormMethod.Post, new { id = "LoginForm",@class="well form-horizontal center-block" }))
    {
        @*<form class="well form-horizontal center-block" action=" " method="post" id="contactform">*@
        <!-- Form Name -->
    <h2>會員登入</h2>
    <hr class="colorgraph"></hr>
    <!-- Text input-->
    <div class="form-group row">
        <label class="col-md-2 control-label"> @Html.LabelFor(m => m.UserID)</label>
        <div class="col-md-8 inputGroupContainer">
            <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                @Html.TextBoxFor(m => m.UserID, new { @class = "form-control" }) @Html.ValidationMessageFor(m => m.UserID, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-md-2 control-label">@Html.LabelFor(m => m.Password)</label>
        <div class="col-md-8 inputGroupContainer">
            <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-hand-right"></i></span>
                @Html.PasswordFor(m => m.Password, new { @class = "form-control" }) @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <!--button-->
    <div class="row">
        <div class="col-md-12"></div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <button class=" btn btn-primary btn-block" type="submit" name="SignIn" value="登入">Sign in</button>
        </div>
        </div>
    @*</form>*@
    }
</div>
    </div><!-- /.container -->
    @section scripts{
        <script>
            $(document).ready(function () {
                $('#LoginForm').formValidation({
                    framework: 'bootstrap',
                    icon: {
                        valid: 'glyphicon glyphicon-ok',
                        invalid: 'glyphicon glyphicon-remove',
                        validating: 'glyphicon glyphicon-refresh'
                    },
                    fields: {
                        UserID: {
                            validators: {
                                notEmpty: {
                                    message: '帳號為必填欄位'
                                },
                                stringLength: {
                                    min: 4,
                                    max: 6,
                                    message: '帳號最少需要4個字元，最大6個字元'
                                },
                                regexp: {
                                    regexp: /^[a-zA-Z0-9_\.]+$/,
                                    message: 'The account can only consist of alphabetical, number, dot and underscore'
                                }
                            }
                        },
                        Password: {
                            validators: {
                                notEmpty: {
                                    message: '密碼為必填欄位'
                                },
                                different: {
                                    field: 'account',
                                    message: '密碼不可與使用者名稱相同'
                                }
                            }
                        }
                    }
                });
            });
        </script>
    }

    @*@using (Html.BeginForm("Login", "User", FormMethod.Post, new { id = "LoginForm" }))
        {
            <div class="container">
                <fieldset>
                    <div class="row mx-auto">
                        <div class="col-md-6 col-md-offset-3" id="LoginFormsize">
                            <h2>會員登入</h2>
                            <h2>
                                <hr class="colorgraph">
                            </h2>
                            <div class="row">
                                <div class="col-md-8 col-md-offset-2">
                                    <div class="form-group">
                                        <h4> @Html.LabelFor(m => m.UserID)</h4>
                                    </div>
                                </div>
                                <div class="col-md-8 col-md-offset-2">
                                    <div class="form-group">
                                        <div class="col-md-12 input-group">
                                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span> @Html.TextBoxFor(m => m.UserID, new { @class = "form-control" }) @Html.ValidationMessageFor(m => m.UserID, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-8 col-md-offset-2">
                                    <div class="form-group">
                                        <h4> @Html.LabelFor(m => m.Password)</h4>
                                    </div>
                                </div>
                                <div class="col-md-8 col-md-offset-2">
                                    <div class="form-group">
                                        <div class="col-md-12 input-group">
                                            <span class="input-group-addon"><i class="glyphicon glyphicon-hand-right"></i></span> @Html.PasswordFor(m => m.Password, new { @class = "form-control" }) @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12 col-sm-2 col-md-2"></div>
                            </div>
                            <hr class="colorgraph">
                            <div class="row">
                                <div class="col-md-6">
                                    <button class=" btn btn-primary btn-block btn-lg" type="submit" name="SignIn" value="登入">確定</button>
                                </div>
                                <div class="col-md-6">
                                    <button class=" btn btn-success btn-block btn-lg" type="reset">取消</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>

        }*@