NorthWindWeb/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using NorthWindWeb.Areas.HelpPage.ModelDescriptions;
using NorthWindWeb.Areas.HelpPage.Models;

namespace NorthWindWeb.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

NorthWindWeb/Controllers/CoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NorthWindWeb.Models;

namespace NorthWindWeb.Controllers
{
    public class CoreController : Controller
    {
        // GET: Core
        public ActionResult Index(Customer m)
        {
            return View(m);
        }
        public ActionResult Menu()
        {
             return View();


        }
    }
}

NorthWindWeb/Controllers/UserController.cs
using Newtonsoft.Json.Linq;
using NorthWindWeb.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;


namespace NorthWindWeb.Controllers
{
    public class UserController : Controller
    {
        UserLogin m = new UserLogin();
        private string connStr = @"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=c:\users\芮君\source\repos\NorthWindWeb\NorthWindWeb\App_Data\northwnd.mdf;Integrated Security = True";

        // GET: User
        [Authorize]
        public ActionResult Index()
        {
            var UserData = JObject.Parse(((FormsIdentity)User.Identity).Ticket.UserData);
            ViewBag.UserName = (String)UserData["UserName"];
            return View();


        }
        public ActionResult Login(String UserID= "" , String Password = "", Boolean IsPersistent = false, String ReturnUrl = "Index")
        {
            if (!String.IsNullOrEmpty(Request.Form.Get("SignIn")))
            {
                //新增一個DataTable資料容器
                DataTable dt = new DataTable();
                //建立資料庫連結
                SqlConnection conn = new SqlConnection(connStr);
                //撰寫SQL語法
                SqlCommand cmd = new SqlCommand(@"select Username from UserProfile where UserID=@UserID and Password=@Password", conn);
                cmd.Parameters.Add(new SqlParameter("@UserID", UserID));
                cmd.Parameters.Add(new SqlParameter("@Password", Password));
                cmd.Parameters.Add(new SqlParameter("@IsPersistent", IsPersistent));
                //打開資料庫連結
                conn.Open();
                //建立資料讀取器
                SqlDataAdapter ad = new SqlDataAdapter(cmd);
                //將讀取的資料放入DataTable
                ad.Fill(dt);
                if (ModelState.IsValid && dt.Rows.Count > 0 && UserID.Length > 0 && Password.Length > 0)
                {
                    String Username2 = dt.Rows[0][0].ToString();
                    string UserData = JObject.FromObject(new { UserName = Username2, Age = 18 }).ToString();

                    FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(1, UserID,
                            DateTime.Now, DateTime.Now.AddMinutes(30), IsPersistent,
                            UserData, FormsAuthentication.FormsCookiePath);
                    HttpCookie cookie = new HttpCookie(FormsAuthentication.FormsCookieName, FormsAuthentication.Encrypt(ticket));
                    if (IsPersistent)
                    {
                        cookie.Expires = DateTime.Now.AddYears(1);
                    }
                    Response.Cookies.Add(cookie);
                }
                else
                {
                    ModelState.AddModelError(
                        "Password", "您輸入的帳號或密碼錯誤,請重新輸入!"
                        );
                    if (!ModelState.IsValidField("Password"))
                    {
                        var emptyValue = new ValueProviderResult(
                            string.Empty,
                            string.Empty,
                            System.Globalization.CultureInfo.CurrentCulture);

                        ModelState.SetModelValue(
                            "Password",
                            emptyValue);
                    }
                    return View(m);
                }
                return Redirect(ReturnUrl);
            }
            else
            {
                return View();
            }
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index");   
        }
    }
}

NorthWindWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Kendo")
    @Scripts.Render("~/bundles/modernizr")
</head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("應用程式名稱", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/validate")
    @RenderSection("scripts", required: false)
</body>
</html>

NorthWindWeb/Views/Shared/_LayoutNorthWind.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Kendo")
    @Scripts.Render("~/bundles/modernizr")
</head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("南風進銷存", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="navbar-text">Hi! @ViewBag.UserName</li>
                        <li>@Html.ActionLink("登出", "Logout", "User", new { area = "" }, null)</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row">
            <div class="col-md-2">
                @{
                    Html.RenderAction("Menu", "Core");
                }
            </div>
            <div class="col-md-8">
                @RenderBody()
            </div>
        </div>
        <footer>
            <p>&copy; @DateTime.Now.Year – PIC MVC課堂實作-@ViewBag.UserName</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/validate")
    @Scripts.Render("~/bundles/Kendo")
    @RenderSection("scripts", required: false)
</body>
</html>